version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:

  - govet
  - errcheck
  - staticcheck
  - unused
  - ineffassign

  # - revive
  - misspell

  - gocyclo
  - dupl
  - goconst
  - unconvert

  - gosec
  - prealloc
  - bodyclose

  - errorlint

  - whitespace
  - exhaustive
  - nilerr

  disable:
  - revive
  - varnamelen
  - wrapcheck
  - nlreturn
  - wsl
